### ISSUE TITLE
Crash on DateTime parse

### ISSUE THREAD

**Issue by ngorevsk** [rodrigosiviero/launchbox_steamscraper#3]
Enter the following URL into the Steam Metadata Downloader:
https://store.steampowered.com/app/1386870/Wraith_The_Oblivion__Afterlife/

Launchbox error popup:
```
String 'May 25, 2021' was not recognized as a valid DateTime.

App:     LaunchBox
Version: 11.11
Type:    System.FormatException
Site:    System.DateTime ParseExact(System.String, System.String, System.IFormatProvider)
Source:  System.Private.CoreLib

   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at SteamScraper.SteamApi.SteamSearch(String appId) in C:\Users\rodri\Source\Repos\launchbox_steamscraper\SteamScraper\SteamApi.cs:line 120
   at SteamScraper.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\rodri\Source\Repos\launchbox_steamscraper\SteamScraper\Form1.cs:line 47
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Recent Log:

   11:51:09 PM Exception
```
This happens with latest version (SteamScraper-v2.3).

Is it because it's a future date?

**Comment by rodrigosiviero** [comment]
I will have a look when I can, I without free time to fix my plugins :(
